import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { setTimeout as delay } from "node:timers/promises";
import { createTelegramSdvgBotService } from "../VBAUT/backend/src/services/telegram-sdvg-bot.js";
import { createMediaFilesUtils } from "../VBAUT/backend/src/services/media-files.js";
const RUSSIA_THEME = "\u0420\u041E\u0421\u0421\u0418\u042F";
const RUSSIA_THEME_LOWER = "\u0440\u043E\u0441\u0441\u0438\u044F";
const tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'vbaut-theme-debug-'));
const mediaRoot = path.join(tempDir, 'PAMPAM');
await fs.mkdir(path.join(mediaRoot,'UNSORTED'), {recursive:true});
await fs.mkdir(path.join(mediaRoot,RUSSIA_THEME), {recursive:true});
await fs.writeFile(path.join(mediaRoot,'UNSORTED','sample.mp4'),'sample','utf8');
const mediaUtils = createMediaFilesUtils({mediaRoot,mediaMaxFilesList:100});
const sentMessages=[]; const deletedMessages=[]; let nextMessageId=100; let getUpdatesStage=0; let assetCounter=0; const createdAssets=new Map(); const botSessions=new Map();
const origFetch=global.fetch; const origToken=process.env.TELEGRAM_BOT_TOKEN; process.env.TELEGRAM_BOT_TOKEN='test-token'; process.env.TELEGRAM_SDVG_ENABLED='1'; process.env.TELEGRAM_SDVG_POLL_TIMEOUT_SEC='1';
function jsonResponse(result){ return {ok:true,text:async()=>JSON.stringify({ok:true,result})}; }
function currentControlMessageId(){ const control=sentMessages.find((item)=>JSON.stringify(item.reply_markup??{}).includes('sdvg_theme:apply')||JSON.stringify(item.reply_markup??{}).includes('sdvg_theme:open')); return control?.message_id??null; }
const mediaDownloader={isAvailable(){return true;},enqueue(){console.log('enqueue'); return {id:'job_1'};},getJob(jobId){if(jobId!=='job_1') return null; return {id:'job_1',status:'completed',progress:'100%',output_files:['sample.mp4'],meta_title:'Smoke Theme Video',meta_uploader:'Smoke Uploader',meta_uploader_url:'https://example.com/uploader',meta_webpage_url:'https://example.com/video',meta_format_note:'720p',meta_resolution:'1280x720'};}};
const deps={appendLinkDecisionsOverride:()=>[],appendEvent:async(...args)=>{console.log('appendEvent',args[1]?.event);},attachAsset:async()=>({}),canonicalizeLinkUrl:(v)=>String(v??'').trim(),collapseDuplicateLinkOnlyTopics:(segments)=>({segments}),createAsset:async(input={})=>{assetCounter+=1;const asset={id:`asset_${assetCounter}`,...input};createdAssets.set(asset.id,asset);console.log('createAsset',asset.local_path);return asset;},ensureMediaDir:mediaUtils.ensureMediaDir,getDocumentMediaDownloads:async()=>({}),getDocumentState:async()=>null,getDocDir:()=>tempDir,getMediaDir:mediaUtils.getMediaDir,getSourceMemory:async()=>({}),getSourceProfiles:async()=>({}),generateSegmentResearchQueries:async()=>[],isHttpUrl:(v)=>/^https?:\/\//i.test(String(v??'')),isMediaAlreadyDownloaded:()=>false,isYtDlpCandidateUrl:(v)=>/^https?:\/\//i.test(String(v??'')),listBotSessions:async()=>[{chat_id:'1',user_id:'',pending_payload_json:{selected_download_theme:RUSSIA_THEME}}],listDocDecisions:async()=>[],listDocuments:async()=>[],listDocSegments:async()=>[],listRunsForSegment:async()=>[],listBotSessionsIndexed:async()=>[],mediaDownloader,mergeResearchScores:()=>[],mergeLinkSegmentsBySection:(l=[],r=[])=>[...l,...r],normalizeDocumentMediaDownloads:(v)=>v??{},normalizeLinkSegmentsInput:(v)=>v??[],normalizeLinkUrl:(v)=>String(v??'').trim(),rankSegmentResearchResults:async()=>[],readOptionalJson:async()=>null,sanitizeMediaTopicName:mediaUtils.sanitizeMediaTopicName,saveVersioned:async()=>1,searchQueries:async()=>[],splitSegmentsAndDecisions:(segments,decisions)=>({segmentsData:segments,decisionsData:decisions}),syncDocumentContext:async()=>null,updateAsset:async(assetId,input={})=>{const existing=createdAssets.get(assetId);const updated={...(existing??{id:assetId}),...input};createdAssets.set(assetId,updated);console.log('updateAsset',assetId,updated.local_path);return updated;},updateSourceProfiles:async()=>({}),upsertBotSession:async(input={})=>{botSessions.set(`${input.chat_id}:${input.user_id??''}`,input);console.log('upsertBotSession',input.pending_payload_json);return input;}};
global.fetch=async(url,init={})=>{ const methodName=String(url).split('/').pop(); if(methodName==='getMe'){console.log('getMe'); return jsonResponse({username:'utsearchbot'});} if(methodName==='getUpdates'){ console.log('getUpdates stage',getUpdatesStage,'control',currentControlMessageId(),'sent',sentMessages.length,'deleted',deletedMessages.join(',')); if(getUpdatesStage===0){getUpdatesStage=1; return jsonResponse([{update_id:1,message:{message_id:1,chat:{id:1},from:{id:11},text:'/download'}}]);} if(getUpdatesStage===1){getUpdatesStage=2; return jsonResponse([{update_id:2,message:{message_id:2,chat:{id:1},from:{id:11},text:'https://example.com/video'}}]);} if(getUpdatesStage===2){const controlMessageId=currentControlMessageId(); if(controlMessageId){getUpdatesStage=3; return jsonResponse([{update_id:3,callback_query:{id:'cb_new',data:'sdvg_theme:new',from:{id:11},message:{message_id:controlMessageId,chat:{id:1}}}}]);} return jsonResponse([]);} if(getUpdatesStage===3){ if(sentMessages.length>=4){getUpdatesStage=4; return jsonResponse([{update_id:4,message:{message_id:300,chat:{id:1},from:{id:11},text:RUSSIA_THEME_LOWER}}]); } return jsonResponse([]);} if(getUpdatesStage===4){const controlMessageId=currentControlMessageId(); if(controlMessageId&&deletedMessages.includes(300)){getUpdatesStage=5; return jsonResponse([{update_id:5,callback_query:{id:'cb_sel',data:'sdvg_theme:sel:0',from:{id:11},message:{message_id:controlMessageId,chat:{id:1}}}}]); } return jsonResponse([]);} return jsonResponse([]);} if(methodName==='sendMessage'){ const payload=JSON.parse(String(init.body??'{}')); const message={message_id:nextMessageId++,text:payload.text,reply_markup:payload.reply_markup??null}; sentMessages.push(message); console.log('sendMessage',message); return jsonResponse(message);} if(methodName==='editMessageText'||methodName==='editMessageReplyMarkup'){ const payload=JSON.parse(String(init.body??'{}')); console.log(methodName,payload.message_id,payload.text??''); return jsonResponse({message_id:Number(payload.message_id)});} if(methodName==='deleteMessage'){ const payload=JSON.parse(String(init.body??'{}')); deletedMessages.push(Number(payload.message_id)); console.log('deleteMessage',payload.message_id); return jsonResponse(true);} if(methodName==='answerCallbackQuery'){return jsonResponse(true);} if(methodName==='sendVideo'||methodName==='sendDocument'){ console.log(methodName); return jsonResponse({message_id:nextMessageId++}); } throw new Error(`Unhandled ${methodName}`); };
const service=createTelegramSdvgBotService(deps); service.start(); await delay(6000); console.log('FINAL sent',JSON.stringify(sentMessages,null,2)); console.log('FINAL deleted',deletedMessages); console.log('FINAL files',await fs.readdir(mediaRoot,{withFileTypes:true}).then(entries=>entries.map(e=>e.name))); service.stop(); global.fetch=origFetch; if(origToken==null) delete process.env.TELEGRAM_BOT_TOKEN; else process.env.TELEGRAM_BOT_TOKEN=origToken; await fs.rm(tempDir,{recursive:true,force:true}); process.exit(0);
